---

## Init

- name: Ensure project directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ docker_project_path }}"
    - "{{ docker_project_path }}/config/netdata"
  tags: ["init"]

## Configure

- name: Configure netdata.conf
  ansible.builtin.copy:
    src: "{{ _netdata_conf }}"
    dest: "{{ docker_project_path }}/config/netdata/"
    owner: "{{ target_user | default(omit) }}"
    group: "{{ target_group | default(target_user | default(omit)) }}"
    mode: '0644'
  with_fileglob:
    - "{{ netdata_config_local_path }}/config/netdata.conf"
  loop_control:
    loop_var: _netdata_conf
  tags: ["configure", "configure-netdata"]
  notify: Restart netdata

- name: Template docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ docker_project_path }}/docker-compose.yml"
    mode: '0644'
    validate: "{{ docker_cmd }} compose -f %s config"
    backup: true

## Run

- name: Start app
  ansible.builtin.include_role: { name: djuuu.docker_project, tasks_from: compose-up }
